#!/usr/bin/env node
/**
 * Refreshes everything in these docs that comes from the API:
 *
 *   1. downloads the OpenAPI document into openapi.json,
 *   2. writes the MDX snippets in snippets/generated/ that the guide pages include,
 *   3. writes one page per endpoint in api-reference/ and the "API reference" tab in docs.json.
 *
 * Run it with `npm run update`. It is idempotent: running it twice on the same document changes
 * nothing. Set OPENAPI_URL to read another server, or OPENAPI_OFFLINE=1 to regenerate from the
 * openapi.json already in the repo.
 *
 * Facts the document does not contain are not written here by hand. Optional extensions the CRM
 * can add to its document (shapes in README.md) are used when present: x-scopes, x-rate-limits,
 * x-transport-errors, x-filter-operators, x-codeSamples.
 */
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SPEC_URL = process.env.OPENAPI_URL ?? 'https://app.marro.si/api/v1/openapi.json';
const SPEC_FILE = join(ROOT, 'openapi.json');
const SNIPPETS = join(ROOT, 'snippets', 'generated');
const REFERENCE_DIR = 'api-reference';
const REFERENCE_TAB = 'API reference';
const HEADER = '{/* Generated by scripts/update.mjs from openapi.json. Do not edit; run `npm run update`. */}\n\n';
const METHODS = ['get', 'post', 'put', 'patch', 'delete'];

// ---------------------------------------------------------------------------------------------
// Loading

async function loadSpec() {
    if (process.env.OPENAPI_OFFLINE !== '1') {
        const response = await fetch(SPEC_URL, { signal: AbortSignal.timeout(30_000) });
        if (!response.ok) throw new Error(`Could not download ${SPEC_URL}: HTTP ${response.status}`);
        const spec = await response.json();
        if (!spec.openapi || !spec.paths) throw new Error(`${SPEC_URL} is not an OpenAPI document`);
        hoistDefs(spec);
        await writeIfChanged(SPEC_FILE, `${JSON.stringify(spec, null, 2)}\n`);
        return spec;
    }
    const spec = JSON.parse(await readFile(SPEC_FILE, 'utf8'));
    hoistDefs(spec);
    return spec;
}

/**
 * The CRM's document nests `$defs` inside each schema and points at them with `#/$defs/Name`,
 * which OpenAPI tools resolve from the document root and so cannot find. This moves every nested
 * definition into `components.schemas` and points the references there. Identical definitions
 * with the same name are shared; a different one with a taken name gets a numbered name.
 */
function hoistDefs(spec) {
    spec.components ??= {};
    spec.components.schemas ??= {};
    const schemas = spec.components.schemas;
    const queue = [spec.paths, ...Object.values(schemas)];
    while (queue.length > 0) {
        const node = queue.shift();
        if (!node || typeof node !== 'object') continue;
        if (!Array.isArray(node) && node.$defs && typeof node.$defs === 'object') {
            const defs = node.$defs;
            delete node.$defs;
            const names = {};
            for (const [name, definition] of Object.entries(defs)) {
                let target = name;
                for (let index = 2; schemas[target] && !sameRefsAside(schemas[target], definition, defs, name); index += 1) target = `${name}${index}`;
                names[name] = target;
            }
            const rewrite = (value) => {
                if (!value || typeof value !== 'object') return;
                if (Array.isArray(value)) { value.forEach(rewrite); return; }
                const match = typeof value.$ref === 'string' ? value.$ref.match(/^#\/\$defs\/(.+)$/) : null;
                if (match && names[match[1]]) value.$ref = `#/components/schemas/${names[match[1]]}`;
                Object.values(value).forEach(rewrite);
            };
            rewrite(node);
            rewrite(defs);
            for (const [name, definition] of Object.entries(defs)) {
                if (!schemas[names[name]]) {
                    schemas[names[name]] = definition;
                    queue.push(definition);
                }
            }
        }
        for (const value of Array.isArray(node) ? node : Object.values(node)) if (value && typeof value === 'object') queue.push(value);
    }
}

/** Whether an already-hoisted schema is the same definition (compared with its refs not yet rewritten). */
function sameRefsAside(existing, definition) {
    const plain = (value) => JSON.stringify(value, (key, item) => (key === '$ref' && typeof item === 'string' ? item.replace(/^#\/(\$defs|components\/schemas)\/([A-Za-z_]+?)\d*$/, '$2') : item));
    return plain(existing) === plain(definition);
}

const written = new Set();

async function writeIfChanged(file, content) {
    written.add(file);
    let current = null;
    try { current = await readFile(file, 'utf8'); } catch { /* new file */ }
    if (current === content) return;
    await mkdir(dirname(file), { recursive: true });
    await writeFile(file, content);
    console.log(`wrote ${file.slice(ROOT.length + 1)}`);
}

// ---------------------------------------------------------------------------------------------
// Text helpers

/** Escapes text for MDX: braces and angle brackets outside `code`, pipes everywhere in tables. */
function mdx(text = '', { table = false } = {}) {
    const parts = String(text).split(/(`[^`]*`)/g).map((part) => {
        if (part.startsWith('`') && part.endsWith('`') && part.length > 1) return table ? part.replaceAll('|', '\\|') : part;
        let out = part.replace(/[{}<>]/g, (char) => `&#${char.charCodeAt(0)};`);
        if (table) out = out.replaceAll('|', '\\|');
        return out;
    });
    const joined = parts.join('');
    return table ? joined.replace(/\s*\n+\s*/g, ' ') : joined;
}

function table(headers, rows) {
    if (rows.length === 0) return '';
    return [
        `| ${headers.join(' | ')} |`,
        `| ${headers.map(() => '---').join(' | ')} |`,
        ...rows.map((row) => `| ${row.map((cell) => mdx(cell, { table: true }) || ' ').join(' | ')} |`),
    ].join('\n');
}

function fence(lang, code, title = '') {
    const ticks = code.includes('```') ? '````' : '```';
    return `${ticks}${lang}${title ? ` ${title}` : ''}\n${code}\n${ticks}`;
}

function slug(text) {
    return String(text).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function shellQuote(text) {
    return `'${text.replaceAll("'", `'\\''`)}'`;
}

// ---------------------------------------------------------------------------------------------
// Reading the document

function operations(spec) {
    const list = [];
    for (const [path, item] of Object.entries(spec.paths)) {
        for (const method of METHODS) {
            const op = item[method];
            if (!op) continue;
            const tag = op.tags?.[0] ?? 'Other';
            const id = op.operationId ?? slug(`${method} ${path}`);
            list.push({ path, method, op, tag, id, page: `${REFERENCE_DIR}/${slug(tag)}/${id}` });
        }
    }
    return list;
}

function resolve(schema, root) {
    if (!schema?.$ref) return schema ?? {};
    const [, kind, name] = schema.$ref.match(/^#\/(\$defs|components\/schemas)\/(.+)$/) ?? [];
    const target = kind === '$defs' ? root?.$defs?.[name] : kind ? globalThis.SPEC.components?.schemas?.[name] : undefined;
    return target ? { ...target, ...Object.fromEntries(Object.entries(schema).filter(([key]) => key !== '$ref')) } : schema;
}

/** A short readable type, like "string (email)", "integer", "object", "array of string". */
function typeOf(input, root) {
    const schema = resolve(input, root);
    const variants = schema.anyOf ?? schema.oneOf;
    if (variants) {
        const types = variants.filter((variant) => variant.type !== 'null').map((variant) => typeOf(variant, root));
        return types.length < variants.length ? `${types.join(' or ')} or null` : types.join(' or ');
    }
    if (schema.enum) return schema.enum.map((value) => JSON.stringify(value)).join(', ');
    const type = Array.isArray(schema.type) ? schema.type.filter((item) => item !== 'null').join(' or ') : schema.type;
    if (type === 'array') return `array of ${schema.items ? typeOf(schema.items, root) : 'any'}`;
    if (type === 'string' && schema.format) return `string (${schema.format})`;
    return type ?? 'object';
}

/** Error responses, read from descriptions in the form "CODE: when". */
function errorResponses(op) {
    return Object.entries(op.responses ?? {}).flatMap(([status, response]) => {
        const match = response.description?.match(/^([A-Z][A-Z0-9_]+): ([\s\S]*)$/);
        return match ? [{ status, code: match[1], when: match[2].trim() }] : [];
    });
}

/** Scopes as the document states them: per operation (security) and named in the scheme. */
function scopes(spec, ops) {
    const scheme = Object.values(spec.components?.securitySchemes ?? {})[0] ?? {};
    const extension = scheme['x-scopes'];
    const labels = new Map();
    for (const match of (scheme.description ?? '').matchAll(/`([a-z0-9_.]+)` \(([^)]+)\)/g)) labels.set(match[1], match[2]);
    const byScope = new Map();
    for (const item of ops) {
        for (const requirement of item.op.security ?? spec.security ?? []) {
            for (const list of Object.values(requirement)) {
                for (const scope of list) {
                    if (!byScope.has(scope)) byScope.set(scope, []);
                    byScope.get(scope).push(item);
                }
            }
        }
    }
    const ids = [...new Set([...labels.keys(), ...byScope.keys(), ...Object.keys(extension ?? {})])];
    return ids.map((id) => ({
        id,
        label: extension?.[id]?.label ?? labels.get(id) ?? '',
        description: extension?.[id]?.description ?? '',
        module: extension?.[id]?.module ?? '',
        operations: byScope.get(id) ?? [],
    }));
}

function link(item) {
    return `[${item.op.summary ?? `${item.method.toUpperCase()} ${item.path}`}](/${item.page})`;
}

// ---------------------------------------------------------------------------------------------
// Snippets

function overviewSnippet(spec, ops) {
    const server = spec.servers?.[0]?.url ?? '';
    const prefix = commonPrefix(ops.map((item) => item.path));
    const tags = [...new Set(ops.map((item) => item.tag))];
    const lines = [
        mdx(spec.info?.description ?? ''),
        '',
        'Base URL:',
        '',
        fence('text', `${server}${prefix}`),
        '',
        `The full specification is an OpenAPI ${spec.openapi} document at [${server}${prefix}/openapi.json](${server}${prefix}/openapi.json). Import it into Postman or a client generator.`,
        '',
    ];
    for (const tag of tags) {
        const description = spec.tags?.find((item) => item.name === tag)?.description;
        lines.push(`### ${mdx(tag)}`, '', ...(description ? [mdx(description), ''] : []));
        lines.push(table(['Endpoint', 'Method', 'Path'], ops.filter((item) => item.tag === tag).map((item) => [
            link(item).replaceAll('|', ''), item.method.toUpperCase(), `\`${item.path}\``,
        ])), '');
    }
    return lines.join('\n');
}

function commonPrefix(paths) {
    if (paths.length === 0) return '';
    const split = paths.map((path) => path.split('/'));
    const out = [];
    for (let index = 0; index < split[0].length; index += 1) {
        const segment = split[0][index];
        if (segment.includes('{') || !split.every((parts) => parts[index] === segment && parts.length > index + 1)) break;
        out.push(segment);
    }
    return out.join('/');
}

function authSnippet(spec, ops) {
    const [name, scheme] = Object.entries(spec.components?.securitySchemes ?? {})[0] ?? [];
    if (!scheme) return '';
    const server = spec.servers?.[0]?.url ?? '';
    // The plain GET that the most kinds of key may call, so the example works for any key.
    const reach = (item) => (item.op.security ?? spec.security ?? []).length;
    const sample = ops.filter((item) => item.method === 'get' && !item.path.includes('{')).sort((a, b) => reach(b) - reach(a))[0] ?? ops[0];
    const header = scheme.type === 'http' && scheme.scheme === 'bearer'
        ? 'Send the key in the `Authorization` header as a bearer token: `Authorization: Bearer <key>`.'
        : `Security scheme \`${name}\`: ${scheme.type}.`;
    const lines = [mdx(header), ''];
    if (scheme.description) lines.push(mdx(scheme.description), '');
    lines.push(fence('bash', `curl "${server}${sample.path}" \\\n  -H "Authorization: Bearer $MARRO_API_KEY"`), '');
    const transport = spec['x-transport-errors'];
    if (Array.isArray(transport) && transport.length > 0) {
        lines.push('Requests are refused before the key is checked when:', '');
        lines.push(table(['Status', 'Code', 'When'], transport.map((error) => [String(error.status), `\`${error.code}\``, error.when])), '');
    }
    return lines.join('\n');
}

function scopesSnippet(spec, ops) {
    const list = scopes(spec, ops);
    const withDescription = list.some((scope) => scope.description);
    const headers = ['Scope', 'Name', ...(withDescription ? ['Allows'] : []), 'Endpoints'];
    const lines = [table(headers, list.map((scope) => [
        `\`${scope.id}\``,
        scope.label,
        ...(withDescription ? [scope.description] : []),
        scope.operations.map((item) => link(item)).join(', '),
    ])), ''];
    const scheme = Object.values(spec.components?.securitySchemes ?? {})[0] ?? {};
    const keyTypes = scheme['x-key-types'];
    if (Array.isArray(keyTypes) && keyTypes.length > 0) {
        lines.push('### Kinds of key', '', table(['Kind', 'Scopes', 'Expires after', 'Use it for'], keyTypes.map((kind) => [
            kind.name,
            (kind.scopes ?? []).map((scope) => `\`${scope}\``).join(', ') || 'Chosen when created',
            kind.lifetimeDays ? `${kind.lifetimeDays} days` : 'Never',
            kind.description ?? '',
        ])), '');
    }
    return lines.join('\n');
}

function errorsSnippet(spec, ops) {
    const errorSchema = spec.components?.schemas?.Error;
    const lines = [];
    if (errorSchema) {
        const inner = resolve(errorSchema.properties?.error ?? {}, errorSchema);
        lines.push('Every error has this shape:', '', fence('json', JSON.stringify({ error: exampleFor(inner, errorSchema) }, null, 2)), '');
        const fields = Object.entries(inner.properties ?? {});
        lines.push(table(['Field', 'Type', 'Description'], fields.map(([key, value]) => [
            `\`error.${key}\`${(inner.required ?? []).includes(key) ? '' : ' (optional)'}`, typeOf(value, errorSchema), value.description ?? '',
        ])), '');
    }

    const codes = new Map();
    for (const item of ops) {
        for (const error of errorResponses(item.op)) {
            const key = `${error.status} ${error.code}`;
            if (!codes.has(key)) codes.set(key, { ...error, whens: new Set(), ops: [] });
            codes.get(key).whens.add(error.when);
            codes.get(key).ops.push(item);
        }
    }
    const transport = Array.isArray(spec['x-transport-errors']) ? spec['x-transport-errors'] : [];
    for (const error of transport) {
        const key = `${error.status} ${error.code}`;
        if (!codes.has(key)) codes.set(key, { status: String(error.status), code: error.code, whens: new Set([error.when]), ops: [] });
    }
    const all = [...codes.values()].sort((a, b) => Number(a.status) - Number(b.status) || a.code.localeCompare(b.code));
    const everywhere = (entry) => entry.ops.length === ops.length;
    lines.push('### Every code', '');
    lines.push(table(['Status', 'Code', 'When', 'Returned by'], all.map((entry) => [
        entry.status,
        `\`${entry.code}\``,
        [...entry.whens].join(' '),
        entry.ops.length === 0 ? 'Any endpoint' : everywhere(entry) ? 'Every endpoint' : entry.ops.map((item) => link(item)).join(', '),
    ])), '');
    return lines.join('\n');
}

/** A placeholder value for a schema, for the error shape example. */
function exampleFor(input, root) {
    const schema = resolve(input, root);
    if (schema.example !== undefined) return schema.example;
    if (schema.type === 'object' && schema.properties) {
        return Object.fromEntries(Object.entries(schema.properties).map(([key, value]) => [key, exampleFor(value, root)]));
    }
    if (schema.type === 'object') return {};
    if (schema.type === 'array') return [];
    if (schema.type === 'integer' || schema.type === 'number') return 0;
    if (schema.type === 'boolean') return true;
    return 'string';
}

function limitsSnippet(spec, ops) {
    const limits = spec['x-rate-limits'];
    const lines = [];
    if (Array.isArray(limits) && limits.length > 0) {
        lines.push(table(['Limit', 'Requests', 'Per'], limits.map((limit) => [limit.label ?? limit.scope, String(limit.limit), limit.window ?? 'hour'])), '');
        if (spec['x-max-body-bytes']) lines.push(`Request bodies are limited to ${Math.round(spec['x-max-body-bytes'] / 1000)} KB.`, '');
    }
    const rateLimited = new Set();
    for (const item of ops) {
        for (const error of errorResponses(item.op)) if (error.status === '429') rateLimited.add(`\`${error.code}\` (429): ${error.when}`);
    }
    for (const text of rateLimited) lines.push(mdx(text), '');
    const retryAfter = ops.some((item) => item.op.responses?.['429']?.headers?.['Retry-After']);
    if (retryAfter) lines.push('The `Retry-After` header gives the number of seconds to wait.', '');
    return lines.join('\n');
}

function filteringSnippet(spec, ops) {
    const list = ops.find((item) => item.method === 'get' && item.op.parameters?.some((parameter) => parameter.name === 'filter'));
    if (!list) return '';
    const parameter = list.op.parameters.find((item) => item.name === 'filter');
    const server = spec.servers?.[0]?.url ?? '';
    const lines = [`${link(list)} takes a \`filter\` query parameter.`, '', mdx(parameter.description ?? ''), ''];
    const sample = parameter.example ?? parameter.description?.match(/`(\[.*?\])`/)?.[1];
    if (sample) {
        lines.push(fence('bash', `curl -G "${server}${list.path}" \\\n  -H "Authorization: Bearer $MARRO_API_KEY" \\\n  --data-urlencode ${shellQuote(`filter=${typeof sample === 'string' ? sample : JSON.stringify(sample)}`)}`), '');
    }
    const operators = parameter['x-filter-operators'] ?? list.op['x-filter-operators'];
    if (operators) {
        if (operators.maxFilters) lines.push(`Up to ${operators.maxFilters} conditions; all must match.`, '');
        lines.push(table(['Field type', 'Operator', 'Meaning', 'Takes'], (operators.byType ?? []).flatMap((group) => group.operators.map((operator, index) => [
            index === 0 ? group.types.join(', ') : '',
            `\`${operator.id}\``,
            operator.label ?? '',
            operator.takes ?? '',
        ]))), '');
    }
    const others = list.op.parameters.filter((item) => item.in === 'query' && item.name !== 'filter');
    if (others.length > 0) {
        lines.push('Other query parameters on this endpoint:', '');
        lines.push(table(['Parameter', 'Type', 'Description'], others.map((item) => [`\`${item.name}\``, typeOf(item.schema), item.description ?? ''])), '');
    }
    return lines.join('\n');
}

function captureSnippet(spec, ops) {
    const capture = ops.find((item) => item.id === 'capture-lead') ?? ops.find((item) => item.path.endsWith('/capture'));
    if (!capture) return '';
    const server = spec.servers?.[0]?.url ?? '';
    const endpoint = `${server}${capture.path}`;
    const body = capture.op.requestBody?.content?.['application/json'];
    const schema = body?.schema ?? {};
    const example = body?.example ?? {};
    const required = new Set(schema.required ?? []);
    const lines = [
        `${link(capture)}: \`${capture.method.toUpperCase()} ${capture.path}\``,
        '',
        mdx(capture.op.description ?? ''),
        '',
        '### Code',
        '',
        '<CodeGroup>',
        '',
        ...codeSamples(capture, endpoint, example).flatMap((sample) => [fence(sample.lang, sample.source, sample.label), '']),
        '</CodeGroup>',
        '',
        '### Request body',
        '',
        table(['Field', 'Type', 'Description'], Object.entries(schema.properties ?? {}).map(([key, value]) => [
            `\`${key}\`${required.has(key) ? ' (required)' : ''}`, typeOf(value, schema), value.description ?? resolve(value, schema).description ?? '',
        ])),
        '',
    ];
    const headers = (capture.op.parameters ?? []).filter((item) => item.in === 'header');
    if (headers.length > 0) {
        lines.push('### Headers', '', table(['Header', 'Description'], headers.map((item) => [`\`${item.name}\``, item.description ?? ''])), '');
    }
    lines.push('### Responses', '', table(['Status', 'Meaning'], Object.entries(capture.op.responses ?? {}).map(([status, response]) => [status, response.description ?? ''])), '');
    return lines.join('\n');
}

/** x-codeSamples from the document if it has them; otherwise built from its request example. */
function codeSamples(item, endpoint, example) {
    const given = item.op['x-codeSamples'];
    if (Array.isArray(given) && given.length > 0) {
        return given.map((sample) => ({ lang: sample.lang?.toLowerCase() ?? 'text', label: sample.label ?? sample.lang ?? '', source: sample.source }));
    }
    const fields = Object.keys(example.fields ?? {});
    const jsKey = (key) => (/^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key));
    const nextjs = `// app/api/enquiry/route.ts on your website. It runs on the server, so the key stays secret.
// Your form posts to /api/enquiry; this sends the enquiry on to Marro.
export async function POST(request: Request) {
  const form = await request.json();
  // One ID per submission. Send the same one again if you retry.
  const submissionId = form.submissionId ?? crypto.randomUUID();

  const response = await fetch(${JSON.stringify(endpoint)}, {
    method: "POST",
    headers: {
      Authorization: \`Bearer \${process.env.MARRO_API_KEY}\`,
      "Content-Type": "application/json",
      "Idempotency-Key": submissionId,
    },
    body: JSON.stringify({
      name: form.name,
      phone: form.phone,
      email: form.email,
      source: "Website",${fields.length > 0 ? `\n      fields: {\n${fields.map((key) => `        ${jsKey(key)}: ${/^[A-Za-z_$][\w$]*$/.test(key) ? `form.${key}` : `form[${JSON.stringify(key)}]`},`).join('\n')}\n      },` : ''}
      attribution: {
        pageUrl: form.pageUrl,
        referrer: form.referrer,
        formName: "Contact form",
      },
    }),
    signal: AbortSignal.timeout(10_000),
  });

  if (!response.ok) {
    // Keep the enquiry and retry later with the same submissionId.
    console.error("Marro capture failed", response.status, await response.text());
  }
  return Response.json({ ok: true });
}`;
    const php = `<?php
// In wp-config.php (never in a theme file or in JavaScript):
// define('MARRO_API_KEY', 'your-api-key');

$response = wp_remote_post('${endpoint}', [
    'timeout' => 10,
    'headers' => [
        'Authorization'   => 'Bearer ' . MARRO_API_KEY,
        'Content-Type'    => 'application/json',
        // One ID per submission; reuse it if you retry.
        'Idempotency-Key' => wp_generate_uuid4(),
    ],
    'body' => wp_json_encode([
        'name'   => sanitize_text_field($_POST['name'] ?? ''),
        'phone'  => sanitize_text_field($_POST['phone'] ?? ''),
        'email'  => sanitize_email($_POST['email'] ?? ''),
        'source' => 'Website',${fields.length > 0 ? `\n        'fields' => [\n${fields.map((key) => `            '${key}' => sanitize_text_field($_POST['${key}'] ?? ''),`).join('\n')}\n        ],` : ''}
        'attribution' => [
            'pageUrl'  => esc_url_raw(wp_get_referer() ?: ''),
            'formName' => 'Contact form',
        ],
    ]),
]);

if (is_wp_error($response) || wp_remote_retrieve_response_code($response) >= 300) {
    // Keep the enquiry (for example, email it to yourself) so no lead is lost.
    error_log('Marro capture failed: ' . (is_wp_error($response) ? $response->get_error_message() : wp_remote_retrieve_body($response)));
}`;
    const curl = [
        `curl -X POST "${endpoint}" \\`,
        '  -H "Authorization: Bearer $MARRO_API_KEY" \\',
        '  -H "Content-Type: application/json" \\',
        '  -H "Idempotency-Key: $(uuidgen)" \\',
        `  -d ${shellQuote(JSON.stringify(example, null, 2))}`,
    ].join('\n');
    return [
        { lang: 'ts', label: 'Next.js', source: nextjs },
        { lang: 'php', label: 'PHP / WordPress', source: php },
        { lang: 'bash', label: 'cURL', source: curl },
    ];
}

// ---------------------------------------------------------------------------------------------
// API reference pages and navigation

async function writeReference(spec, ops) {
    for (const item of ops) {
        const frontmatter = [
            '---',
            `title: ${JSON.stringify(item.op.summary ?? `${item.method.toUpperCase()} ${item.path}`)}`,
            `openapi: ${JSON.stringify(`${item.method.toUpperCase()} ${item.path}`)}`,
            '---',
            '',
        ].join('\n');
        await writeIfChanged(join(ROOT, `${item.page}.mdx`), frontmatter);
    }
    await removeStale(join(ROOT, REFERENCE_DIR));

    const docsFile = join(ROOT, 'docs.json');
    const docs = JSON.parse(await readFile(docsFile, 'utf8'));
    const tags = [...new Set(ops.map((item) => item.tag))];
    const tab = {
        tab: REFERENCE_TAB,
        openapi: 'openapi.json',
        groups: tags.map((tag) => ({ group: tag, pages: ops.filter((item) => item.tag === tag).map((item) => item.page) })),
    };
    const tabs = docs.navigation.tabs.filter((item) => item.tab !== REFERENCE_TAB);
    docs.navigation.tabs = [...tabs, tab];
    await writeIfChanged(docsFile, `${JSON.stringify(docs, null, 2)}\n`);
}

/** Deletes generated files that the current document no longer produces. */
async function removeStale(directory) {
    let entries = [];
    try { entries = await readdir(directory, { withFileTypes: true }); } catch { return; }
    for (const entry of entries) {
        const path = join(directory, entry.name);
        if (entry.isDirectory()) {
            await removeStale(path);
            if ((await readdir(path)).length === 0) await rm(path, { recursive: true });
        } else if (!written.has(path)) {
            await rm(path);
            console.log(`removed ${path.slice(ROOT.length + 1)}`);
        }
    }
}

// ---------------------------------------------------------------------------------------------

const spec = await loadSpec();
globalThis.SPEC = spec;
const ops = operations(spec);
const snippets = {
    'overview.mdx': overviewSnippet(spec, ops),
    'authentication.mdx': authSnippet(spec, ops),
    'scopes.mdx': scopesSnippet(spec, ops),
    'errors.mdx': errorsSnippet(spec, ops),
    'rate-limits.mdx': limitsSnippet(spec, ops),
    'filtering.mdx': filteringSnippet(spec, ops),
    'capture.mdx': captureSnippet(spec, ops),
};
for (const [name, content] of Object.entries(snippets)) {
    await writeIfChanged(join(SNIPPETS, name), `${HEADER}${content.trim()}\n`);
}
await removeStale(SNIPPETS);
await writeReference(spec, ops);
console.log(`${ops.length} endpoints, ${Object.keys(snippets).length} snippets: up to date.`);
